module.exports = {
  env: {
    browser: true,
    es2021: true,
    jest: true,
  },
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'prettier', 'react', 'react-hooks'],
  extends: [
    'plugin:react/recommended',
    'plugin:@typescript-eslint/recommended',
    'prettier',
    'plugin:prettier/recommended',
  ],
  rules: {
    'no-constant-binary-expression': 2,
    'prettier/prettier': 2,
    '@typescript-eslint/no-explicit-any': 0,
    'react-hooks/rules-of-hooks': 2,
    'react-hooks/exhaustive-deps': 2,
    'react/react-in-jsx-scope': 'off',
    'react/prop-types': 'off',
    'react/display-name': 0,
    'react/jsx-no-undef': 0,
    'react/jsx-uses-react': 0,
    'react/jsx-uses-vars': 2,
    'react/jsx-no-duplicate-props': 2,
    'react/jsx-no-comment-textnodes': 2,
    'react/jsx-key': 2,
    'react/jsx-no-target-blank': 2,
    'react/jsx-no-useless-fragment': 2,
    'react/jsx-pascal-case': 2,
  },
};
